// src/routes/+page.svelte
<script lang="ts">
import CheckIcon from '@lucide/svelte/icons/check';
import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';
import { toast } from 'svelte-sonner';
import { goto } from '$app/navigation';
import { Badge } from '$lib/components/ui/badge';
import { Button } from '$lib/components/ui/button';
import { Card, CardContent } from '$lib/components/ui/card';
import { Input } from '$lib/components/ui/input';
import {
	type Answers,
	computeReadiness,
	type FlagArea,
	getContent,
	visibleQuestions,
} from '$lib/content';
import DailyFlags from '$lib/DailyFlags.svelte';
import DeepAssessment from '$lib/DeepAssessment.svelte';
import Prose from '$lib/Prose.svelte';
import * as m from '$lib/paraglide/messages';
import {
	programWeeks,
	rehabToday,
	resolveDay,
	resolveExerciseIds,
	resolveSwapIndex,
	taskKey,
} from '$lib/plan';
import Rehab from '$lib/Rehab.svelte';
import SectionHeading from '$lib/SectionHeading.svelte';
import { appState, type ReadinessEntry, today } from '$lib/state.svelte';
import {
	acwr,
	completedSessions,
	probeReadiness,
	readinessInsights,
	sessionsLast7,
	trainStreak,
	weekLoad,
} from '$lib/stats';
import { STUDIES } from '$lib/studies';
import TrendChart from '$lib/TrendChart.svelte';
import { toMetricCanonical } from '$lib/units';
import { cn } from '$lib/utils';

// Daily bodyweight nudge — it anchors the % bodyweight strength estimates.
let bwInput = $state('');
const bwLoggedToday = $derived(appState.metrics.bodyweight.some((e) => e.date === today()));
function logBodyweight() {
	const n = Number.parseFloat(bwInput);
	if (Number.isNaN(n)) return;
	appState.metrics.bodyweight.push({
		date: today(),
		at: Date.now(),
		v: toMetricCanonical('bodyweight', n),
	});
	bwInput = '';
}

const content = getContent();

// Today's planned protocol = the microcycle slot for the real weekday.
const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const weekday = WEEKDAYS[new Date().getDay()];
const week = $derived(appState.currentWeek);
const day = $derived(resolveDay(content, week, weekday));
const dayLabel = $derived(content.days.find((d) => d.k === weekday)?.label ?? weekday);

interface Task {
	id: string;
	label: string;
	done: boolean;
}

const tasks = $derived<Task[]>(
	resolveExerciseIds(content, week, weekday).flatMap((exId) => {
		const ex = content.exercises[exId];
		// `rest` is not a task — a day with no tasks is a rest day.
		if (!ex) return [];
		const idx = resolveSwapIndex(week, weekday, exId);
		if (exId === 'rest' && idx === 0) return [];
		return [{ id: exId, label: ex.name, done: !!appState.taskDone[taskKey(week, weekday, exId)] }];
	}),
);
const isRestDay = $derived(tasks.length === 0);

// Final week of the block → prompt a retest to calibrate the next one.
let reassessDismissed = $state(false);
const needsReassess = $derived(
	!reassessDismissed && appState.assessment != null && week >= programWeeks(),
);

let answers = $state<Answers>({});
// Climbing-specific objective probe: today's quick max pull (kg), optional.
let probeValue = $state<number | null>(null);
const probeResult = $derived(probeReadiness(appState.probeLog, probeValue));
// Objective signals: EWMA acute:chronic ratio (null < ~3 weeks), Foster training
// monotony, and the max-pull probe vs baseline — all feed the recommendation.
const loadSignals = $derived({
	acwr: acwr(appState.workouts, Date.now())?.status ?? null,
	monotony:
		weekLoad(appState.workouts, Date.now())?.status === 'monotonous' ? ('high' as const) : null,
	probe: probeResult.status,
});
// Personalization from logged history: baseline, trend and outcome calibration.
const insights = $derived(readinessInsights(appState.readinessLog));
// Adaptive: show the core, reveal follow-ups only when they'd change the result.
const visible = $derived(visibleQuestions(answers));
const visibleQuiz = $derived(content.quiz.filter((q) => visible.includes(q.id)));
const complete = $derived(visible.every((id) => answers[id] != null));
const readiness = $derived(complete ? computeReadiness(answers, loadSignals, insights) : null);
const verdict = $derived(readiness ? content.verdicts[readiness.verdict] : null);
const flags = $derived(readiness?.flags ?? []);

// Today's score vs the user's personal norm.
const baselineLabel = $derived.by(() => {
	if (!readiness || insights.baseline == null) return null;
	const d = readiness.score - insights.baseline;
	return d <= -10 ? m.rd_vs_below() : d >= 10 ? m.rd_vs_above() : m.rd_vs_usual();
});

// Honest framing of the score: the weighting is a reasoned default heuristic
// until enough post-session feedback (the calibration threshold) personalizes it.
const calibrated = $derived(appState.readinessLog.filter((e) => e.outcome != null).length >= 4);
const scoreNote = $derived(calibrated ? m.rd_note_tuned() : m.rd_note_heuristic());

// Post-session outcome (set after training) feeds the calibration loop.
const todayEntry = $derived(appState.readinessLog.find((e) => e.date === today()));
function setOutcome(v: number) {
	const e = appState.readinessLog.find((x) => x.date === today());
	if (!e) return;
	e.outcome = v;
	toast.success(m.rd_outcome_saved());
}

const studyUrl = (id?: string) => (id ? STUDIES.find((s) => s.id === id)?.url : undefined);

// The wellness dimensions behind the readiness score (for the breakdown).
const WELLNESS_DIMS = [
	{ id: 'sleep', label: () => m.rd_sleep() },
	{ id: 'fatigue', label: () => m.rd_fatigue() },
	{ id: 'soreness', label: () => m.rd_soreness() },
	{ id: 'stress', label: () => m.rd_stress() },
	{ id: 'mood', label: () => m.rd_mood() },
];
const breakdown = $derived(
	WELLNESS_DIMS.filter((d) => answers[d.id] != null).map((d) => ({
		label: d.label(),
		v: answers[d.id],
	})),
);

function startRehabToday(area: FlagArea) {
	rehabToday(content, week, weekday, area);
	toast.success(m.toast_rehab_today());
}

let deepArea = $state<FlagArea | null>(null);

const streak = $derived(trainStreak(appState.workouts));
const last7 = $derived(sessionsLast7(appState.workouts));
const totalSessions = $derived(completedSessions(appState.workouts));

function pick(qid: string, value: number) {
	answers = { ...answers, [qid]: value };
}

function recheck() {
	answers = {};
	probeValue = null;
}

// Auto-log the readiness check once every shown question is answered: upsert
// today's entry with the full response + conclusion. No manual save needed; the
// early-return on no-change keeps the write from re-triggering this effect.
$effect(() => {
	if (!complete || !readiness) return;
	const d = today();
	const rl = appState.readinessLog;
	const existing = rl.find((e) => e.date === d);
	const flags = readiness.flags.map((f) => ({
		id: f.id,
		severity: f.severity,
		...(f.area ? { area: f.area } : {}),
	}));
	const snap = { ...answers };
	if (
		existing &&
		existing.score === readiness.score &&
		existing.verdict === readiness.verdict &&
		JSON.stringify(existing.answers) === JSON.stringify(snap) &&
		JSON.stringify(existing.flags) === JSON.stringify(flags)
	)
		return;
	const entry: ReadinessEntry = {
		date: d,
		at: existing?.at ?? Date.now(),
		verdict: readiness.verdict,
		score: readiness.score,
		answers: snap,
		flags,
		...(existing?.outcome != null ? { outcome: existing.outcome } : {}),
	};
	if (existing) Object.assign(existing, entry);
	else rl.push(entry);
});

// Bank today's objective probe reading (for the personal baseline) once the
// check is complete and a value has been entered.
$effect(() => {
	if (!complete) return;
	const v = probeValue;
	if (v == null || Number.isNaN(v) || v <= 0) return;
	const d = today();
	const pe = appState.probeLog.find((p) => p.date === d);
	if (pe) {
		if (pe.value !== v) pe.value = v;
	} else {
		appState.probeLog.push({ date: d, at: Date.now(), value: v });
	}
});
</script>

<section class="animate-in fade-in duration-300">
	<SectionHeading title={m.sec_today()} />
	<p class="mb-[26px] max-w-[62ch] text-[15px] text-ink-dim">
		<Prose value={m.lede_today()} />
	</p>


	{#if !bwLoggedToday}
		<div class="mb-[22px] flex items-center gap-2 rounded-xl border border-line bg-panel px-4 py-2.5">
			<span class="flex-1 text-[13px] text-ink-dim">
				{m.bw_prompt()} ({appState.prefs.weight})
			</span>
			<Input
				type="number"
				step="any"
				bind:value={bwInput}
				class="h-8 w-24 bg-panel-2 text-center text-sm"
			/>
			<Button size="sm" class="bg-chalk text-bg hover:bg-chalk/90" onclick={logBodyweight}>
				{m.btn_save()}
			</Button>
		</div>
	{/if}

	{#if needsReassess}
		<div class="mb-[22px] flex items-center gap-3 rounded-xl border border-gold/40 bg-gold/10 px-4 py-3">
			<span class="flex-1 text-[13px] text-ink-dim">{m.reassess_note()}</span>
			<a href="/metrics" class="font-mono text-[11px] tracking-wider text-gold uppercase hover:underline">
				{m.reassess_cta()}
			</a>
			<button
				type="button"
				aria-label={m.btn_close()}
				class="text-ink-faint transition hover:text-ink"
				onclick={() => (reassessDismissed = true)}
			>
				✕
			</button>
		</div>
	{/if}

	<!-- Today's plan + per-task checklist -->
	<Card class="mb-[22px] gap-3 border-l-[3px] p-5" style="border-left-color: {day.color}">
		<div class="flex items-baseline justify-between gap-2">
			<span class="font-bold">{m.td_today_label()} · {dayLabel}</span>
			<div class="flex items-baseline gap-2.5">
				<a href="/week" class="font-mono text-[11px] text-ink-faint hover:text-ink">
					{m.week_label({ n: week })}
				</a>
				<span class="font-mono text-[11px] tracking-wider uppercase" style:color={day.color}>
					{day.load}
				</span>
			</div>
		</div>
		{#if isRestDay}
			<p class="text-sm text-teal">{m.td_rest_day()}</p>
			<p class="text-xs text-ink-dim"><Prose value={day.sec} /></p>
		{:else}
			<div class="flex flex-col gap-2">
				{#each tasks as task (task.id)}
					<a
						href="/train?ex={task.id}"
						class={cn(
							'flex items-center gap-2.5 rounded-lg border px-3 py-2 text-sm transition',
							task.done
								? 'border-teal/40 bg-teal/5 text-ink-faint'
								: 'border-line bg-panel-2 text-ink-dim hover:border-flag hover:text-chalk'
						)}
					>
						{#if task.done}
							<CheckIcon class="size-4 flex-none text-teal" />
						{/if}
						<span class={cn('flex-1', task.done && 'line-through')}>{task.label}</span>
						<span class="font-mono text-[10px] tracking-wider text-ink-faint uppercase">
							{task.done ? m.lbl_done() : m.td_open_train()}
						</span>
						<ChevronRightIcon class="size-4" />
					</a>
				{/each}
			</div>
		{/if}
	</Card>

	<div class="mb-[22px] grid grid-cols-3 gap-3">
		<Card class="items-center gap-0 p-3.5 text-center">
			<span class="font-mono text-[26px] leading-none font-bold text-flag">{streak}</span>
			<span class="mt-1 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
				{m.stat_streak()}
			</span>
		</Card>
		<Card class="items-center gap-0 p-3.5 text-center">
			<span class="font-mono text-[26px] leading-none font-bold text-chalk">{last7}<span
					class="text-sm text-ink-faint">/7</span
				></span>
			<span class="mt-1 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
				{m.stat_week_sessions()}
			</span>
		</Card>
		<Card class="items-center gap-0 p-3.5 text-center">
			<span class="font-mono text-[26px] leading-none font-bold text-chalk">{totalSessions}</span>
			<span class="mt-1 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
				{m.stat_total()}
			</span>
		</Card>
	</div>

	<Card class="mb-[22px] gap-0 p-6">
		<CardContent class="space-y-[22px] p-0">
			{#each visibleQuiz as q, qi (q.id)}
				<div class="animate-in fade-in duration-200">
					<div class="mb-1 text-[15px] font-semibold">
						<span class="mr-2 font-mono text-xs text-flag">0{qi + 1}</span>{q.q}
					</div>
					{#if q.why}
						<p class="mb-2 max-w-[60ch] text-[12px] leading-snug text-ink-faint">
							{q.why}{#if studyUrl(q.study)}
								<a
									href={studyUrl(q.study)}
									target="_blank"
									rel="noopener noreferrer"
									class="ml-1 whitespace-nowrap text-flag hover:underline">{m.rd_evidence()}</a
								>{/if}
						</p>
					{/if}
					<div class="flex flex-wrap gap-2">
						{#each q.a as a (a.t)}
							<button
								type="button"
								onclick={() => pick(q.id, a.v)}
								class={cn(
									'min-w-[120px] flex-1 rounded-[9px] border px-3 py-[11px] text-left text-[13.5px] transition',
									answers[q.id] === a.v
										? 'border-flag bg-flag/10 font-semibold text-chalk'
										: 'border-line bg-panel-2 text-ink-dim hover:border-ink-faint hover:text-ink'
								)}
							>
								{a.t}
							</button>
						{/each}
					</div>
				</div>
			{/each}

			<!-- Optional climbing-specific objective probe: a quick max finger pull. -->
			<div class="border-t border-line pt-[22px] animate-in fade-in duration-200">
				<div class="mb-1 text-[15px] font-semibold">
					<span class="mr-2 font-mono text-xs text-flag">+</span>{m.rd_probe_label()}
				</div>
				<p class="mb-2 max-w-[60ch] text-[12px] leading-snug text-ink-faint">
					{m.rd_probe_why()}{#if studyUrl('probe')}
						<a
							href={studyUrl('probe')}
							target="_blank"
							rel="noopener noreferrer"
							class="ml-1 whitespace-nowrap text-flag hover:underline">{m.rd_evidence()}</a
						>{/if}
				</p>
				<div class="flex items-center gap-2">
					<Input
						type="number"
						inputmode="decimal"
						step="any"
						min="0"
						value={probeValue ?? ''}
						oninput={(e) =>
							(probeValue = e.currentTarget.value === '' ? null : e.currentTarget.valueAsNumber)}
						placeholder={m.rd_probe_ph()}
						class="w-32 bg-panel-2 text-sm"
					/>
					<span class="text-xs text-ink-faint">kg</span>
					{#if probeResult.baseline != null}
						<span class="font-mono text-[11px] text-ink-faint">
							{m.rd_probe_baseline({ kg: probeResult.baseline })}{#if probeResult.deficitPct != null}
								· <span
									class={cn(
										probeResult.deficitPct >= 6
											? 'text-flag'
											: probeResult.deficitPct <= -5
												? 'text-teal'
												: 'text-ink-faint'
									)}
									>{probeResult.deficitPct > 0 ? '−' : '+'}{Math.abs(probeResult.deficitPct)}%</span
								>{/if}
						</span>
					{:else if probeValue != null}
						<span class="font-mono text-[11px] text-ink-faint">{m.rd_probe_building()}</span>
					{/if}
				</div>
			</div>
		</CardContent>
	</Card>

	{#if verdict && readiness}
		<Card class="overflow-hidden p-0 animate-in fade-in duration-300">
			<div class="flex items-center gap-3.5 border-b border-line p-5">
				<span class="size-3.5 flex-none rounded-full" style:background={verdict.color}></span>
				<div class="min-w-0 flex-1">
					<div class="text-[19px] font-extrabold tracking-tight">{verdict.title}</div>
					<div class="font-mono text-[11px] tracking-wider text-ink-faint uppercase">
						{verdict.tag}
					</div>
				</div>
				<div class="flex-none text-right">
					<div class="font-mono text-[22px] leading-none font-bold text-chalk">{readiness.score}</div>
					<div class="font-mono text-[9px] tracking-wider text-ink-faint uppercase">
						{m.rd_score()}
					</div>
					{#if baselineLabel}
						<div class="mt-0.5 font-mono text-[9px] text-ink-faint">{baselineLabel}</div>
					{/if}
				</div>
			</div>
			<div class="p-5 text-[14.5px] text-ink-dim">
				<div><Prose value={verdict.text} /></div>
				{#if breakdown.length}
					<div class="mt-3 flex flex-wrap gap-1.5">
						{#each breakdown as b (b.label)}
							<span
								class={cn(
									'rounded-full border px-2 py-0.5 font-mono text-[10px]',
									b.v >= 7
										? 'border-teal/40 text-teal'
										: b.v >= 4
											? 'border-gold/40 text-gold'
											: 'border-flag/40 text-flag'
								)}
							>
								{b.label} {b.v}/10
							</span>
						{/each}
					</div>
				{/if}
				<p class="mt-2 text-[11px] leading-snug text-ink-faint italic">{scoreNote}</p>
				{#if tasks[0]}
					<p class="mt-2.5 text-[13px] text-ink-faint">
						{m.td_applies()} <b class="text-chalk">{tasks[0].label}</b>
					</p>
				{/if}
				<div class="mt-3.5 flex flex-wrap gap-2">
					{#each verdict.focus as f, i (f)}
						<Badge
							variant="outline"
							class={cn(
								'border-line font-mono text-[11px] font-normal text-ink-dim',
								i === 0 && 'border-flag text-flag'
							)}
						>
							<Prose value={f} />
						</Badge>
					{/each}
				</div>
				<div class="mt-[18px] flex flex-wrap items-center gap-2.5">
					<Button variant="outline" onclick={recheck}>{m.td_recheck()}</Button>
					<Button href="/week" variant="ghost">{m.btn_view_protocol()}</Button>
					<span class="font-mono text-[10px] tracking-wider text-ink-faint uppercase">
						{m.train_autosave()}
					</span>
				</div>

				{#if todayEntry && todayEntry.outcome == null}
					<div class="mt-4 border-t border-line pt-3.5">
						<div class="mb-2 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
							{m.rd_outcome_q()}
						</div>
						<div class="flex flex-wrap gap-2">
							{#each [{ v: 3, l: m.rd_outcome_strong() }, { v: 2, l: m.rd_outcome_ok() }, { v: 1, l: m.rd_outcome_flat() }, { v: 0, l: m.rd_outcome_bailed() }] as o (o.v)}
								<Button
									variant="outline"
									size="sm"
									class="border-line text-xs"
									onclick={() => setOutcome(o.v)}
								>
									{o.l}
								</Button>
							{/each}
						</div>
					</div>
				{:else if todayEntry?.outcome != null}
					<p class="mt-3 font-mono text-[11px] text-teal">{m.rd_outcome_saved()}</p>
				{/if}
			</div>
		</Card>
	{/if}

	{#if appState.readinessLog.length > 1}
		<Card class="mb-[22px] gap-2 p-5">
			<span class="font-mono text-[10px] tracking-wider text-ink-faint uppercase">
				{m.readiness_trend()}
			</span>
			<TrendChart
				points={appState.readinessLog.slice(-14).map((e) => ({ value: e.score, label: e.date }))}
				color="var(--teal)"
				fmt={(v) => String(Math.round(v))}
			/>
		</Card>
	{/if}

	<DailyFlags
		{flags}
		{content}
		onRehab={startRehabToday}
		onPlan={() => goto('/settings')}
		onDeep={(a) => (deepArea = a)}
	/>

	<!-- Injury / rehab entry point: start (or end) a conservative rehab block right here. -->
	<div class="mt-[22px]">
		<Rehab />
	</div>
</section>

{#if deepArea}
	<DeepAssessment area={deepArea} onClose={() => (deepArea = null)} />
{/if}

// src/routes/index.tsx
// TODAY — Direction A.
//
// The screen that decides whether "dense and calm" survives contact with a
// phone. It carries, in one scroll: the read, the five wellness dimensions
// behind it, the plan and the work the read holds back, the carry-forward from
// a missed day, three counters, a fourteen-point trend, two watch-outs with
// their advice, a nine-question check, the bodyweight nudge, and two injury
// entry points.
//
// The ordering rule is *decision first, evidence second, input last*: the
// verdict is the top of the screen because it is the answer; the check that
// produced it is near the bottom because it is already answered. That inverts
// the SvelteKit screen, where the quiz came first and the athlete scrolled past
// nine questions to reach the one line they opened the app for.
//
// The screen is genuinely live. It re-runs the real `computeReadiness` against
// whatever the check currently says, using the same load signals and personal
// baseline the fixture derived — so changing an answer moves the score, the
// verdict, the watch-outs and which exercises the plan holds back. #42 puts the
// training logic out of scope for the redesign; this renders it rather than
// re-deciding it.
import { createFileRoute, Link } from '@tanstack/react-router';
import { Check, ChevronRight, ExternalLink } from 'lucide-react';
import { useMemo, useState } from 'react';
import {
	type Answers,
	computeReadiness,
	type FlagArea,
	getContent,
	visibleQuestionsOrdered,
} from '$lib/content';
import * as m from '$lib/paraglide/messages';
import { capByVerdict } from '$lib/readinessPlan';
import { acwr, readinessInsights, weekLoad } from '$lib/stats';
import { cn } from '$lib/utils';
import { OUTCOME_LABEL, WELLNESS_LABEL } from '../components/format';
import { DeepCheckSheet, RehabStarter } from '../components/InjurySection';
import { ReadinessCheck } from '../components/ReadinessCheck';
import { Sparkline } from '../components/Sparkline';
import { button, card, chip, Eyebrow, input, Meter, Prose, Section, Stat } from '../components/ui';
import { getPrototypeFixtures, type QuizFixture } from '../prototype-fixtures';

export const Route = createFileRoute('/')({ component: Today });

/** Severity → surface tone. `info` deliberately gets no tint: three tinted
 *  panels in a row is how a calm screen turns into a warning screen. */
const FLAG_CARD = { stop: 'stop', warn: 'warn', info: 'plain' } as const;
const FLAG_CHIP = { stop: 'stop', warn: 'warn', info: 'neutral' } as const;

function Today() {
	const now = useMemo(() => Date.now(), []);
	const fx = useMemo(() => getPrototypeFixtures(now), [now]);
	const content = useMemo(() => getContent(), []);
	const t = fx.today;

	const [answers, setAnswers] = useState<Answers>(t.answers);
	const [done, setDone] = useState<Record<string, boolean>>(() =>
		Object.fromEntries(t.tasks.map((task) => [task.exId, task.done])),
	);
	const [outcome, setOutcome] = useState<number | null>(null);
	const [missedTaken, setMissedTaken] = useState(false);
	const [bw, setBw] = useState('');
	const [bwLogged, setBwLogged] = useState(false);
	const [deepOpen, setDeepOpen] = useState(false);
	const [checkOpen, setCheckOpen] = useState(true);

	// The same inputs the fixture used, re-derived so the check is live: load
	// signals read the history *behind* today (a session logged today cannot be
	// part of the load that decided whether to train today), and the personal
	// baseline reads the logged checks, which likewise exclude today's.
	const { readiness, insights } = useMemo(() => {
		const history = fx.state.workouts.filter((w) => w.at !== t.iso);
		const ins = readinessInsights(fx.state.readinessLog);
		const load = {
			acwr: acwr(history, now)?.status ?? null,
			monotony: weekLoad(history, now)?.status === 'monotonous' ? ('high' as const) : null,
		};
		return { readiness: computeReadiness(answers, load, ins), insights: ins };
	}, [answers, fx, t.iso, now]);

	const verdict = content.verdicts[readiness.verdict];
	const heldSet = useMemo(
		() =>
			new Set(
				capByVerdict(
					t.tasks.map((x) => x.exId),
					readiness.verdict,
				).held,
			),
		[t.tasks, readiness.verdict],
	);

	// Follow-ups appear and disappear as the core answers change, so the rendered
	// list is rebuilt from the same `visibleQuestionsOrdered` the app uses rather
	// than from the fixture's frozen snapshot.
	const questions = useMemo<QuizFixture[]>(
		() =>
			visibleQuestionsOrdered(answers).map(({ id, sub }) => {
				const q = content.quiz.find((x) => x.id === id);
				return {
					id,
					sub,
					question: q?.q ?? id,
					...(q?.why ? { why: q.why } : {}),
					...(q?.study ? { study: q.study } : {}),
					options: (q?.a ?? []).map((o) => ({ label: o.t, value: o.v })),
					answer: answers[id] ?? null,
				};
			}),
		[answers, content],
	);
	const answered = questions.filter((q) => q.answer != null).length;

	const delta = insights.baseline == null ? 0 : readiness.score - insights.baseline;
	const vsBaseline =
		delta <= -10 ? m.rd_vs_below() : delta >= 10 ? m.rd_vs_above() : m.rd_vs_usual();
	const breakdown = ['sleep', 'fatigue', 'soreness', 'stress', 'mood']
		.filter((id) => answers[id] != null)
		.map((id) => ({ id, value: answers[id] }));
	const nextTask = t.tasks.find((x) => !done[x.exId] && !heldSet.has(x.exId));
	const bwSeries = t.bodyweight.series;
	const bwDelta = bwSeries.length > 1 ? t.bodyweight.latestKg - bwSeries[0].v : 0;

	return (
		<div className="flex flex-col gap-4">
			{/* ---- day header. Two lines, no card: the frame for everything below. */}
			<header className="flex items-baseline justify-between gap-2 pt-1">
				<div className="min-w-0">
					<h1 className="text-[17px] leading-tight font-semibold text-ink">
						{m.td_today_label()} · {t.weekdayLabel}
					</h1>
					<p className="num mt-0.5 truncate text-[11px] text-ink-faint">{t.dateLabel}</p>
				</div>
				<span className="num shrink-0 text-[11px] text-ink-faint">
					{m.week_label({ n: t.week })}
				</span>
			</header>

			{/* ---- the read. The anchor of the screen and the only place a 30px
			     number appears; everything else is 22px or smaller. */}
			<div className={card({ pad: 'none' })}>
				<div className="flex items-start gap-2.5 p-3.5">
					<span
						className="mt-1.5 size-2.5 shrink-0 rounded-full"
						style={{ background: verdict.color }}
					/>
					<div className="min-w-0 flex-1">
						<h2 className="text-[15px] leading-tight font-semibold text-ink">{verdict.title}</h2>
						<Eyebrow className="mt-0.5">{verdict.tag}</Eyebrow>
					</div>
					<div className="shrink-0 text-right">
						<div className="num text-[30px] leading-none font-bold text-chalk">
							{readiness.score}
						</div>
						<Eyebrow className="mt-0.5">{m.rd_score()}</Eyebrow>
						<div className="mt-0.5 text-[10px] text-ink-faint">{vsBaseline}</div>
					</div>
				</div>

				<div className="border-t border-line-soft px-3.5 py-3">
					<p className="prose-inline text-[13px] leading-snug text-ink-dim">
						<Prose value={verdict.text} />
					</p>
					<div className="mt-2 flex flex-wrap gap-1">
						{verdict.focus.map((f, i) => (
							<span key={f} className={chip({ tone: i === 0 ? 'stop' : 'neutral' })}>
								<Prose value={f} />
							</span>
						))}
					</div>
				</div>

				{/* The five wellness dimensions, one per line. Two columns would fit
				    in English and clip "Recuperação" in pt-BR; five 18px rows is the
				    price of a breakdown that is readable in both. */}
				<div className="flex flex-col gap-1 border-t border-line-soft px-3.5 py-3">
					{breakdown.map((b) => (
						<Meter key={b.id} label={WELLNESS_LABEL[b.id]?.() ?? b.id} value={b.value} />
					))}
					<p className="mt-1.5 text-[10.5px] leading-snug text-ink-faint italic">
						{t.scoreNote === 'tuned' ? m.rd_note_tuned() : m.rd_note_heuristic()}
					</p>
				</div>

				{nextTask ? (
					<div className="border-t border-line-soft px-3.5 py-2.5 text-[12px] text-ink-faint">
						{m.td_applies()} <b className="font-semibold text-chalk">{nextTask.label}</b>
					</div>
				) : null}

				{/* Post-session outcome: the input that turns the heuristic weighting
				    into a personal one. */}
				<div className="border-t border-line-soft px-3.5 py-3">
					<Eyebrow>{m.rd_outcome_q()}</Eyebrow>
					<div className="mt-1.5 grid grid-cols-4 gap-1">
						{[3, 2, 1, 0].map((v) => (
							<button
								key={v}
								type="button"
								aria-pressed={outcome === v}
								onClick={() => setOutcome(v)}
								className={button({
									kind: 'quiet',
									class: cn('px-1 text-[12px]', outcome === v && 'border-teal/50 text-teal'),
								})}
							>
								{OUTCOME_LABEL[v]()}
							</button>
						))}
					</div>
					{outcome != null ? (
						<p className="mt-1.5 text-[11px] text-teal">{m.rd_outcome_saved()}</p>
					) : null}
				</div>
			</div>

			{/* ---- the plan. */}
			<Section
				label={`${t.day.type} · ${t.day.load}`}
				meta={
					<Link to="/train" className="text-ink-dim">
						{m.btn_view_protocol()}
					</Link>
				}
			>
				<div className={card({ pad: 'none' })}>
					{/* The block phase belongs here, not in the page header: it is the
					    reason today's prescription looks the way it does, and in the
					    header it was a truncated fragment next to the date. */}
					<div className="border-b border-line-soft px-3 py-2">
						<p className="text-[11.5px] leading-snug font-medium text-chalk">{t.phase.name}</p>
						<p className="mt-0.5 text-[11px] leading-snug text-ink-faint">{t.phase.banner}</p>
						<p className="mt-1 text-[11px] leading-snug text-ink-faint">
							{t.day.prime} · {t.day.sec}
						</p>
					</div>
					<ul>
						{t.tasks.map((task) => {
							const isDone = done[task.exId];
							const held = heldSet.has(task.exId) && !isDone;
							return (
								<li
									key={task.exId}
									className={cn(
										'flex items-center gap-2 border-b border-line-soft px-3 py-2 last:border-b-0',
										held && 'bg-panel-2/40',
									)}
								>
									<button
										type="button"
										aria-pressed={isDone}
										aria-label={task.label}
										onClick={() => setDone((p) => ({ ...p, [task.exId]: !p[task.exId] }))}
										className={cn(
											'flex size-[22px] shrink-0 items-center justify-center rounded-md border transition-colors',
											isDone
												? 'border-teal/60 bg-teal/15 text-teal'
												: 'border-line text-transparent',
										)}
									>
										<Check size={13} strokeWidth={2.6} />
									</button>
									<span
										className={cn(
											'min-w-0 flex-1 truncate text-[13.5px]',
											isDone ? 'text-ink-faint line-through' : held ? 'text-ink-faint' : 'text-ink',
										)}
									>
										{task.label}
									</span>
									{held ? (
										<span className={chip({ tone: 'warn' })}>{m.td_held()}</span>
									) : isDone ? (
										<span className={chip({ tone: 'ok' })}>{m.lbl_done()}</span>
									) : (
										<Link
											to="/train"
											className="flex shrink-0 items-center gap-0.5 text-[11px] text-ink-dim"
										>
											{m.td_open_train()}
											<ChevronRight size={13} />
										</Link>
									)}
								</li>
							);
						})}
					</ul>

					{/* Carry-forward lives inside the plan rather than as a banner above
					    it: it is one more thing that could be trained today. */}
					{t.missed && !missedTaken ? (
						<div className="flex items-center gap-2 border-t border-line px-3 py-2">
							<span className="min-w-0 flex-1 text-[12px] leading-snug text-ink-dim">
								{m.td_missed({ day: t.missed.weekdayLabel })}
								<span className="text-ink-faint"> · {t.missed.labels.join(' · ')}</span>
							</span>
							<button
								type="button"
								onClick={() => setMissedTaken(true)}
								className={button({ class: 'shrink-0' })}
							>
								{m.td_missed_do()}
							</button>
						</div>
					) : null}
				</div>
			</Section>

			{/* ---- counters. One card, three readings, divider-separated. */}
			<div className={card({ pad: 'sm', class: 'flex divide-x divide-line-soft' })}>
				<Stat accent value={t.stats.streak} label={m.stat_streak()} />
				<Stat value={t.stats.last7} suffix="/7" label={m.stat_week_sessions()} />
				<Stat value={t.stats.total} label={m.stat_total()} />
			</div>

			{/* ---- the trend. The one chart the rebuild still has data for. */}
			<Section
				label={m.readiness_trend()}
				meta={
					<span className="num">
						{insights.baseline != null ? `⌀ ${Math.round(insights.baseline)} · ` : ''}
						{vsBaseline}
					</span>
				}
			>
				<div className={card({ pad: 'sm' })}>
					<Sparkline
						points={t.trendPoints}
						baseline={insights.baseline}
						current={readiness.score}
					/>
					<div className="num mt-1 flex justify-between text-[9px] text-ink-faint">
						<span>{t.trendPoints[0]?.label}</span>
						<span>{t.trendPoints[t.trendPoints.length - 1]?.label}</span>
					</div>
				</div>
			</Section>

			{/* ---- watch-outs. */}
			{readiness.flags.length ? (
				<Section label={m.flags_heading()}>
					<div className="flex flex-col gap-2">
						{readiness.flags.map((f) => {
							const c = content.flags[f.id];
							if (!c) return null;
							return (
								<div key={f.id} className={card({ pad: 'sm', tone: FLAG_CARD[f.severity] })}>
									<div className="flex items-baseline gap-2">
										<span className="flex-1 text-[13.5px] font-semibold text-ink">{c.title}</span>
										<span className={chip({ tone: FLAG_CHIP[f.severity] })}>{f.severity}</span>
									</div>
									<p className="prose-inline mt-1 text-[12.5px] leading-snug text-ink-dim">
										<Prose value={c.text} />
									</p>
									<div className="mt-1.5 flex flex-wrap gap-1">
										{c.focus.map((x) => (
											<span key={x} className={chip({ tone: 'ghost' })}>
												<Prose value={x} />
											</span>
										))}
									</div>
									{f.area ? (
										<div className="mt-2 flex flex-wrap gap-1.5">
											<button
												type="button"
												onClick={() => setDeepOpen(true)}
												className={button({ size: 'sm' })}
											>
												{m.flag_deep()}
											</button>
											<button type="button" className={button({ size: 'sm' })}>
												{m.flag_rehab_today()}
											</button>
											<button type="button" className={button({ kind: 'bare', size: 'sm' })}>
												{m.flag_rehab_plan()}
											</button>
										</div>
									) : null}
								</div>
							);
						})}
					</div>
				</Section>
			) : null}

			{/* ---- the check. Answered, so it opens as a receipt with the form
			     underneath; the toggle collapses it back to the receipt. */}
			<Section
				label={m.log_readiness()}
				meta={
					<button type="button" onClick={() => setCheckOpen((v) => !v)} className="text-ink-dim">
						{checkOpen ? m.btn_close() : m.td_recheck()}
					</button>
				}
			>
				<div className={card({ pad: 'sm' })}>
					<div className="flex items-baseline justify-between gap-2 text-[12px] text-ink-faint">
						<span className="num">
							{answered}/{questions.length}
						</span>
						<button
							type="button"
							onClick={() => setAnswers({})}
							className="text-[11px] text-ink-dim underline decoration-line underline-offset-2"
						>
							{m.td_recheck()}
						</button>
					</div>
					{checkOpen ? (
						<div className="mt-3 border-t border-line-soft pt-3">
							<ReadinessCheck
								questions={questions}
								answers={answers}
								onPick={(id, v) => setAnswers((prev) => ({ ...prev, [id]: v }))}
							/>
						</div>
					) : null}
				</div>
			</Section>

			{/* ---- bodyweight. A nudge, one row, with the series it feeds. */}
			<Section label={m.field_bodyweight()}>
				<div className={card({ pad: 'sm' })}>
					<div className="flex items-center gap-2">
						<div className="min-w-0 flex-1">
							<div className="num text-[18px] leading-none font-bold text-chalk">
								{t.bodyweight.latestKg}
								<span className="text-[11px] text-ink-faint"> kg</span>
								<span
									className={cn(
										'ml-1.5 text-[11px]',
										bwDelta < 0 ? 'text-teal' : bwDelta > 0 ? 'text-gold' : 'text-ink-faint',
									)}
								>
									{bwDelta > 0 ? '+' : ''}
									{Math.round(bwDelta * 10) / 10}
								</span>
							</div>
							<div className="mt-1 w-full">
								<Sparkline
									points={bwSeries.map((s) => ({ value: s.v, label: s.date }))}
									color="var(--violet)"
									height={20}
								/>
							</div>
						</div>
					</div>
					{t.bodyweight.promptToday && !bwLogged ? (
						<div className="mt-2 flex items-center gap-2 border-t border-line-soft pt-2">
							<label className="min-w-0 flex-1 text-[12px] text-ink-dim" htmlFor="bw">
								{m.bw_prompt()}
							</label>
							<input
								id="bw"
								className={input({ class: 'h-8 w-20 shrink-0' })}
								type="number"
								inputMode="decimal"
								step="any"
								value={bw}
								onChange={(e) => setBw(e.currentTarget.value)}
							/>
							<button
								type="button"
								disabled={bw === ''}
								onClick={() => setBwLogged(true)}
								className={button({ kind: 'primary', class: 'shrink-0' })}
							>
								{m.btn_save()}
							</button>
						</div>
					) : null}
				</div>
			</Section>

			{/* ---- injury. Last section on purpose — rarely needed, never hidden. */}
			<Section label={m.rehab_title()}>
				<div className={card({ pad: 'none' })}>
					<div className="border-b border-line-soft p-3">
						<RehabStarter />
					</div>
					<button
						type="button"
						onClick={() => setDeepOpen(true)}
						className="flex w-full items-center gap-2 p-3 text-left transition-colors active:bg-panel-2"
					>
						<span className="min-w-0 flex-1">
							<span className="block text-[13px] font-medium text-ink">
								{t.deep.assessment.title}
							</span>
							<span className="num mt-0.5 block text-[11px] text-ink-faint">
								{m.deep_last({ score: t.deep.last.score, date: t.deep.last.date })}
							</span>
						</span>
						<ChevronRight size={15} className="shrink-0 text-ink-faint" />
					</button>
					<p className="border-t border-line-soft px-3 py-2 text-[10.5px] leading-snug text-ink-faint">
						{m.deep_based_on({ source: t.deep.assessment.source })}{' '}
						<a
							href={t.deep.assessment.url}
							target="_blank"
							rel="noopener noreferrer"
							className="inline-flex items-center gap-0.5 whitespace-nowrap text-ink-dim underline decoration-line underline-offset-2"
						>
							{m.deep_source_link()}
							<ExternalLink size={9} />
						</a>
					</p>
				</div>
			</Section>

			<DeepCheckSheet
				area={t.deep.area as FlagArea}
				assessment={t.deep.assessment}
				last={t.deep.last}
				open={deepOpen}
				onOpenChange={setDeepOpen}
			/>
		</div>
	);
}
