// src/components/Log.tsx
// Log — the three chapters of the history.
//
// This is the screen that punishes low density, and the brief says so up front.
// Twenty-six sessions and fourteen readiness checks set as editorial index
// entries is a long scroll, and no amount of typographic care changes that
// arithmetic. Two things keep it navigable without abandoning the direction:
//
//   * **Months are headings, not rows.** Grouping the sessions under a display-size
//     month gives the scroll landmarks, which is what a dense list gets from
//     sheer information and a sparse one has to earn.
//   * **Everything is one line until it is opened.** A closed entry is date,
//     title, and the one number that distinguishes it. The set rows — the densest
//     thing in the whole app — are inside.
//
// It is still the weakest screen for this direction. That is a finding, not a
// bug, and it is on the ticket.
import { useState } from 'react';
import * as m from '$lib/paraglide/messages';
import { getLocale } from '$lib/paraglide/runtime';
import type { WorkoutSet } from '$lib/types';
import type {
	LogFixture,
	LoggedReadinessFixture,
	LoggedSessionFixture,
	SetField,
} from '../prototype-fixtures';
import { Chapter } from './Editorial';

const OUTCOME_LABEL = [
	() => m.rd_outcome_bailed(),
	() => m.rd_outcome_flat(),
	() => m.rd_outcome_ok(),
	() => m.rd_outcome_strong(),
];

const TYPE_LABEL: Record<string, () => string> = {
	rec: () => m.log_type_rec(),
	day: () => m.log_type_day(),
	test: () => m.log_type_test(),
};

const SHOW: Record<Exclude<SetField, 'grip'>, (v: number) => string> = {
	weight: (v) => `${v} kg`,
	edge: (v) => `${v} mm`,
	time: (v) => `${v} s`,
	reps: (v) => `${v}×`,
	rest: (v) => `${v} s`,
	rpe: (v) => `RPE ${v}`,
};

function summarize(set: WorkoutSet, fields: SetField[]): string {
	const parts: string[] = [];
	for (const f of fields) {
		if (f === 'grip') continue;
		const v = set[f];
		if (v == null) continue;
		parts.push(SHOW[f](v));
	}
	return parts.join(' · ');
}

/** An index entry: a heading you can open. The whole Log screen is made of these. */
function Entry({
	eyebrow,
	title,
	titleColor,
	aside,
	children,
}: {
	eyebrow: string;
	title: string;
	titleColor?: string;
	aside?: string;
	children: React.ReactNode;
}) {
	const [open, setOpen] = useState(false);
	return (
		<li className="border-line border-b">
			<button
				type="button"
				aria-expanded={open}
				onClick={() => setOpen((v) => !v)}
				className="flex w-full items-baseline gap-3 py-5 text-left"
			>
				<span className="min-w-0 flex-1">
					<span className="c-eyebrow block">{eyebrow}</span>
					<span
						className="mt-1 block font-display text-[19px] leading-tight"
						style={{ color: titleColor }}
					>
						{title}
					</span>
				</span>
				{aside ? (
					<span className="c-numeral flex-none text-[1.5rem] text-ink-faint">{aside}</span>
				) : null}
			</button>
			{open ? <div className="pb-6">{children}</div> : null}
		</li>
	);
}

function ReadinessEntryRow({ entry }: { entry: LoggedReadinessFixture }) {
	return (
		<Entry
			eyebrow={`${entry.dateLabel} · ${entry.timeLabel}`}
			title={entry.verdict.title}
			titleColor={entry.verdict.color}
			aside={String(entry.score)}
		>
			{entry.responses.length > 0 ? (
				<>
					<p className="c-eyebrow">{m.log_rd_responses()}</p>
					<dl className="mt-2 mb-6">
						{entry.responses.map((r) => (
							<div key={r.question} className="flex items-baseline justify-between gap-4 py-1.5">
								<dt className="text-[13px] text-ink-dim">{r.question}</dt>
								<dd className="flex-none text-[13px] text-ink">{r.answer}</dd>
							</div>
						))}
					</dl>
				</>
			) : null}
			<p className="c-eyebrow">{m.log_rd_conclusion()}</p>
			<p className="mt-1 font-display text-[17px] text-ink">{entry.verdict.title}</p>
			{entry.outcome != null ? (
				<p className="mt-1 text-[13px] text-ink-faint">{OUTCOME_LABEL[entry.outcome]?.() ?? ''}</p>
			) : null}
			{entry.flagTitles.length > 0 ? (
				<ul className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[13px] text-ink-faint">
					{entry.flagTitles.map((t) => (
						<li key={t} className="border-line border-b pb-0.5">
							{t}
						</li>
					))}
				</ul>
			) : null}
		</Entry>
	);
}

function SessionEntryRow({ session }: { session: LoggedSessionFixture }) {
	return (
		<Entry
			eyebrow={`${session.dateLabel} · ${session.weekdayLabel}`}
			title={session.dayType}
			aside={`${session.setCount}`}
		>
			{session.exercises.map((ex) => (
				<div key={ex.exId} className="mb-5">
					<p className="font-display text-[17px] text-ink">{ex.name}</p>
					<ul className="mt-1">
						{ex.sets.map((s, i) => (
							<li
								// A logged set has no identity beyond its position in the exercise.
								// biome-ignore lint/suspicious/noArrayIndexKey: position is the identity
								key={i}
								className="flex items-baseline gap-3 border-line border-b py-1.5 text-[13px]"
							>
								<span className="c-eyebrow w-14 flex-none">{m.c_set_n({ n: i + 1 })}</span>
								<span className="tabular-nums text-ink-dim">{summarize(s, ex.fields)}</span>
								{s.done ? (
									<span className="ml-auto flex-none text-flag">
										<span className="sr-only">{m.lbl_done()}</span>
										<span aria-hidden="true">✓</span>
									</span>
								) : null}
							</li>
						))}
					</ul>
				</div>
			))}
			{session.note ? <p className="text-[13px] text-ink-dim italic">“{session.note}”</p> : null}
			{session.durationMin != null ? (
				<p className="c-eyebrow mt-2">
					{session.durationMin} {m.train_duration()}
				</p>
			) : null}
		</Entry>
	);
}

/** Sessions bucketed by calendar month, newest first, preserving fixture order. */
function byMonth(
	sessions: LoggedSessionFixture[],
): { key: string; label: string; rows: LoggedSessionFixture[] }[] {
	const out: { key: string; label: string; rows: LoggedSessionFixture[] }[] = [];
	for (const s of sessions) {
		const key = s.iso.slice(0, 7);
		let bucket = out.find((b) => b.key === key);
		if (!bucket) {
			const [y, mo] = key.split('-').map(Number);
			bucket = {
				key,
				// A month name is a date format, not app copy — no message key exists or
				// should. `getLocale()` is what makes it Portuguese under pt-BR.
				label: new Date(y, mo - 1, 1).toLocaleDateString(getLocale(), {
					month: 'long',
					year: 'numeric',
				}),
				rows: [],
			};
			out.push(bucket);
		}
		bucket.rows.push(s);
	}
	return out;
}

export function LogReadiness({ log, index }: { log: LogFixture; index: number }) {
	return (
		<Chapter id="log-readiness" index={index} label={m.log_readiness()}>
			<h2 className="c-display text-[clamp(1.75rem,8vw,2.5rem)]">{m.log_readiness()}</h2>
			<ul className="mt-8 border-line border-t">
				{log.readiness.map((r) => (
					<ReadinessEntryRow key={r.iso} entry={r} />
				))}
			</ul>
		</Chapter>
	);
}

export function LogSessions({ log, index }: { log: LogFixture; index: number }) {
	return (
		<Chapter id="log-sessions" index={index} label={m.log_workouts()}>
			<h2 className="c-display text-[clamp(1.75rem,8vw,2.5rem)]">{m.log_workouts()}</h2>
			{byMonth(log.sessions).map((bucket) => (
				<section key={bucket.key} className="mt-10">
					<h3 className="c-display text-[22px] text-ink-faint first-letter:uppercase">
						{bucket.label}
					</h3>
					<ul className="mt-3 border-line border-t">
						{bucket.rows.map((s) => (
							<SessionEntryRow key={s.iso} session={s} />
						))}
					</ul>
				</section>
			))}
		</Chapter>
	);
}

export function LogActivity({ log, index }: { log: LogFixture; index: number }) {
	return (
		<Chapter id="log-activity" index={index} label={m.log_activity()}>
			<h2 className="c-display text-[clamp(1.75rem,8vw,2.5rem)]">{m.log_activity()}</h2>
			{log.activity.length === 0 ? (
				<p className="mt-8 text-[15px] text-ink-dim">{m.log_empty()}</p>
			) : (
				<ul className="mt-8 border-line border-t">
					{log.activity.map((a) => (
						<li key={`${a.date}-${a.type}-${a.label}`} className="border-line border-b py-4">
							<p className="c-eyebrow flex items-baseline gap-3">
								<span>{a.date}</span>
								<span style={{ color: a.color }}>{TYPE_LABEL[a.type]?.() ?? a.type}</span>
							</p>
							<p className="mt-1 font-display text-[19px] text-ink">{a.label}</p>
							{a.note ? <p className="mt-1 text-[13px] text-ink-dim">{a.note}</p> : null}
						</li>
					))}
				</ul>
			)}
		</Chapter>
	);
}

// src/routes/log/+page.svelte
<script lang="ts">
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '$lib/components/ui/accordion';
import { getContent } from '$lib/content';
import type { VerdictId } from '$lib/content/types';
import * as m from '$lib/paraglide/messages';
import { getLocale } from '$lib/paraglide/runtime';
import SectionHeading from '$lib/SectionHeading.svelte';
import SetRows from '$lib/SetRows.svelte';
import { appState } from '$lib/state.svelte';
import type { Col } from '$lib/trainColumns';
import { edgeLabel, weightLabel } from '$lib/units';

// Editable columns for past-workout sets (all fields; values are unit-aware).
const LOG_COLS: Col[] = [
	{ key: 'weight', label: weightLabel },
	{ key: 'edge', label: edgeLabel },
	{ key: 'time', label: m.field_time },
	{ key: 'reps', label: m.field_reps },
	{ key: 'grip', label: m.field_grip },
	{ key: 'rest', label: m.field_rest },
	{ key: 'rpe', label: m.field_rpe },
];

const typeLabel: Record<string, () => string> = {
	rec: m.log_type_rec,
	day: m.log_type_day,
	test: m.log_type_test,
};

const content = getContent();
// Post-session outcome, indexed by the stored value: 0 bailed · 1 flat · 2 as
// expected · 3 strong.
const OUTCOME_LABEL = [
	m.rd_outcome_bailed,
	m.rd_outcome_flat,
	m.rd_outcome_ok,
	m.rd_outcome_strong,
];

function remove(idx: number) {
	appState.log.splice(idx, 1);
}
function removeWorkout(idx: number) {
	appState.workouts.splice(idx, 1);
}
// readinessLog is stored oldest→newest, so removal is by identity (the list is
// reversed for display).
function removeReadiness(entry: (typeof appState.readinessLog)[number]) {
	const i = appState.readinessLog.indexOf(entry);
	if (i >= 0) appState.readinessLog.splice(i, 1);
}

/** Logged time-of-day (HH:MM) for an epoch-ms timestamp. */
const hour = (at: number) =>
	new Date(at).toLocaleTimeString(getLocale(), { hour: '2-digit', minute: '2-digit' });

/** Map a stored answers map back to readable question → chosen-answer pairs. */
function responses(answers?: Record<string, number>): { q: string; a: string }[] {
	if (!answers) return [];
	const out: { q: string; a: string }[] = [];
	for (const q of content.quiz) {
		const v = answers[q.id];
		if (v == null) continue;
		out.push({ q: q.q, a: q.a.find((o) => o.v === v)?.t ?? String(v) });
	}
	return out;
}

/** The conclusion's flag titles. */
const flagTitles = (flags?: { id: string }[]): string[] =>
	(flags ?? []).map((f) => content.flags[f.id]?.title ?? f.id);
</script>

<section class="animate-in fade-in duration-300">
	<SectionHeading title={m.sec_log()} />
	<p class="mb-[26px] max-w-[62ch] text-[15px] text-ink-dim">{m.lede_log()}</p>

	{#if appState.readinessLog.length > 0}
		<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">
			{m.log_readiness()}
		</h3>
		<Accordion type="multiple" class="mb-6 flex flex-col gap-2.5">
			{#each [...appState.readinessLog].reverse() as r, i (r)}
				{@const v = content.verdicts[r.verdict as VerdictId]}
				<AccordionItem value={`r${i}`} class="rounded-xl border border-line bg-panel last:border-b">
					<AccordionTrigger class="px-4 py-3 hover:no-underline">
						<span class="font-mono text-xs text-ink-faint">{r.date} · {hour(r.at)}</span>
						<span
							class="ml-2 flex-none rounded-md px-2 py-0.5 font-mono text-[11px] font-bold tabular-nums"
							style:background="color-mix(in srgb, {v?.color ?? 'var(--ink-faint)'} 18%, transparent)"
							style:color={v?.color ?? 'var(--ink-faint)'}
						>
							{r.score}
						</span>
						<span class="ml-2 flex-1 text-left text-[13px]">
							<b class="text-chalk">{v?.title ?? r.verdict}</b>{#if r.outcome != null}<span
									class="text-ink-faint"
								>
									· {OUTCOME_LABEL[r.outcome]?.() ?? ''}</span
								>{/if}
						</span>
					</AccordionTrigger>
					<AccordionContent class="px-4 pb-4">
						{#if responses(r.answers).length}
							<div class="mb-1.5 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
								{m.log_rd_responses()}
							</div>
							<div class="mb-3 flex flex-col gap-1">
								{#each responses(r.answers) as row (row.q)}
									<div class="flex items-baseline justify-between gap-3 text-[13px]">
										<span class="text-ink-dim">{row.q}</span>
										<span class="flex-none font-semibold text-chalk">{row.a}</span>
									</div>
								{/each}
							</div>
						{/if}
						<div class="mb-1.5 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
							{m.log_rd_conclusion()}
						</div>
						<p class="text-[13px] text-ink-dim">
							<b class="text-chalk">{v?.title ?? r.verdict}</b>
						</p>
						{#if flagTitles(r.flags).length}
							<div class="mt-2 flex flex-wrap gap-1.5">
								{#each flagTitles(r.flags) as t (t)}
									<span class="rounded-full border border-line px-2 py-0.5 text-[11px] text-ink-dim">
										{t}
									</span>
								{/each}
							</div>
						{/if}
						<button
							type="button"
							class="mt-3 font-mono text-[10px] tracking-wider text-ink-faint uppercase hover:text-flag"
							onclick={() => removeReadiness(r)}
						>
							✕ {m.btn_delete()}
						</button>
					</AccordionContent>
				</AccordionItem>
			{/each}
		</Accordion>
	{/if}

	{#if appState.workouts.length > 0}
		<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">
			{m.log_workouts()}
		</h3>
		<Accordion type="multiple" class="mb-6 flex flex-col gap-2.5">
			{#each appState.workouts.slice(0, 60) as w, idx (w)}
				<AccordionItem value={`w${idx}`} class="rounded-xl border border-line bg-panel last:border-b">
					<AccordionTrigger class="px-4 py-3 hover:no-underline">
						<span class="font-mono text-xs text-ink-faint">{w.date}</span>
						<span class="ml-2 flex-1 text-left text-[13px]">
							<b class="text-chalk">{w.day}</b>
							<span class="text-ink-faint">· {w.exercises.length}×</span>
						</span>
					</AccordionTrigger>
					<AccordionContent class="px-4 pb-4">
						{#each w.exercises as ex (ex.exId)}
							<div class="mb-2.5">
								<div class="mb-1 text-[13px] font-semibold text-chalk">{ex.name}</div>
								<SetRows rows={ex.sets} cols={LOG_COLS} onRemove={(i) => ex.sets.splice(i, 1)} />
							</div>
						{/each}
						{#if w.note}<p class="text-[12px] text-ink-dim italic">“{w.note}”</p>{/if}
						<button
							type="button"
							class="mt-2 font-mono text-[10px] tracking-wider text-ink-faint uppercase hover:text-flag"
							onclick={() => removeWorkout(idx)}
						>
							✕ {m.btn_delete()}
						</button>
					</AccordionContent>
				</AccordionItem>
			{/each}
		</Accordion>
	{/if}

	<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">{m.log_activity()}</h3>
	{#if appState.log.length === 0}
		<div class="rounded-xl border border-dashed border-line px-5 py-[46px] text-center text-sm text-ink-faint">
			{m.log_empty()}
		</div>
	{:else}
		<div class="flex flex-col gap-2.5">
			{#each appState.log.slice(0, 120) as entry, idx (entry)}
				<div class="flex items-center gap-3.5 rounded-[10px] border border-line bg-panel px-4 py-3.5">
					<span class="w-[90px] flex-none font-mono text-xs text-ink-faint">{entry.date}</span>
					<span
						class="flex-none rounded-md px-2.5 py-1 font-mono text-[10px] font-bold tracking-wide uppercase"
						style:background="color-mix(in srgb, {entry.color} 18%, transparent)"
						style:color={entry.color}
					>
						{typeLabel[entry.type]?.() ?? entry.type}
					</span>
					<span class="flex-1 text-[13px] text-ink-dim">
						<b class="text-chalk">{entry.label}</b>{entry.note ? ` · ${entry.note}` : ''}
					</span>
					<button
						type="button"
						title="delete"
						onclick={() => remove(idx)}
						class="px-1 text-base text-ink-faint transition hover:text-flag"
					>
						✕
					</button>
				</div>
			{/each}
		</div>
	{/if}
</section>
