// src/routes/log.tsx
// LOG — Direction D.
//
// The screen that argues with the direction. 28 sessions, 14 readiness checks
// and 8 activity rows, at sizes chosen for chalky hands: 28 accordion headers at
// 76px is over five screens of scrolling before anything is even opened, and
// that is with the bodies closed.
//
// Two things absorb it, and both are compromises worth naming on the ticket:
//
//  • The three lists are separated by a rocker rather than stacked, so the
//    screen is one list deep instead of three. That is navigation added to buy
//    back density — the exact move the redesign is supposed to be removing.
//  • Inside an opened session, a set is a single mono line rather than the field
//    grid Train uses. The set grid does not survive at log density. Reading and
//    editing are not the same job, and this direction only makes the editing one
//    big.
import { Accordion } from '@base-ui/react/accordion';
import { Tabs } from '@base-ui/react/tabs';
import { createFileRoute } from '@tanstack/react-router';
import { ChevronDown } from 'lucide-react';
import { useMemo, useState } from 'react';
import * as m from '$lib/paraglide/messages';
import type { WorkoutSet } from '$lib/types';
import { Head, Panel, pill } from '../components/physical';
import {
	getPrototypeFixtures,
	type LoggedSessionFixture,
	type SetField,
} from '../prototype-fixtures';

export const Route = createFileRoute('/log')({ component: Log });

/** Units, not copy — they read the same in both locales. */
const UNIT: Partial<Record<SetField, string>> = {
	weight: 'kg',
	edge: 'mm',
	time: 's',
	rest: 's',
	reps: '×',
	rpe: 'RPE',
};

/** One logged set on one line. The dense form; Train has the big one. */
function setLine(set: WorkoutSet, fields: SetField[]): string {
	return fields
		.map((field) => {
			if (field === 'grip') return set.grip ?? null;
			const value = set[field];
			if (value == null) return null;
			return field === 'rpe' ? `RPE ${value}` : `${value}${UNIT[field] ?? ''}`;
		})
		.filter(Boolean)
		.join(' · ');
}

const OUTCOME_LABEL: Record<number, () => string> = {
	0: () => m.rd_outcome_bailed(),
	1: () => m.rd_outcome_flat(),
	2: () => m.rd_outcome_ok(),
	3: () => m.rd_outcome_strong(),
};

const ACTIVITY_LABEL: Record<string, () => string> = {
	rec: () => m.log_type_rec(),
	day: () => m.log_type_day(),
	test: () => m.log_type_test(),
};

function Log() {
	const fx = useMemo(() => getPrototypeFixtures(), []);
	const log = fx.log;
	const [tab, setTab] = useState('workouts');

	const tabs = [
		{ value: 'workouts', label: m.log_workouts(), count: log.sessions.length },
		{ value: 'readiness', label: m.log_readiness(), count: log.readiness.length },
		{ value: 'activity', label: m.log_activity(), count: log.activity.length },
	];

	return (
		<Tabs.Root value={tab} onValueChange={(next) => setTab(String(next))} className="mt-3">
			{/* A rocker, not a row of text tabs: three 64px slabs, thumb-sized. */}
			<Tabs.List className="well flex gap-1 rounded-lg p-1">
				{tabs.map((entry) => (
					<Tabs.Tab
						key={entry.value}
						value={entry.value}
						// The selected slab is computed here rather than through a
						// `data-selected:` variant: `slab` is a custom utility and the
						// variant would have to generate it, which is fragile enough to
						// be worth not relying on for the direction's core surface.
						className={`flex h-16 flex-1 flex-col items-center justify-center gap-0.5 rounded-md transition-transform duration-75 active:translate-y-[1px] ${
							tab === entry.value ? 'slab text-ink' : 'text-ink-faint'
						}`}
					>
						<span className="max-w-full truncate px-1 text-[13px] leading-tight font-semibold tracking-tight">
							{entry.label}
						</span>
						<span className="font-mono text-[11px] leading-none">{entry.count}</span>
					</Tabs.Tab>
				))}
			</Tabs.List>

			<Tabs.Panel value="workouts">
				<Head right={<span>{m.sessions_count({ n: log.sessions.length })}</span>}>
					{m.log_workouts()}
				</Head>
				<Accordion.Root multiple={false} className="flex flex-col gap-2">
					{log.sessions.map((session) => (
						<SessionRow key={session.iso} session={session} />
					))}
				</Accordion.Root>
			</Tabs.Panel>

			<Tabs.Panel value="readiness">
				<Head right={<span>{log.readiness.length}</span>}>{m.log_readiness()}</Head>
				<Accordion.Root multiple={false} className="flex flex-col gap-2">
					{log.readiness.map((entry) => (
						<Accordion.Item
							key={entry.iso}
							value={entry.iso}
							className="slab overflow-hidden rounded-lg"
						>
							<Accordion.Header>
								<Accordion.Trigger className="group flex w-full items-center gap-3 px-3 py-3 text-left transition-transform duration-75 active:translate-y-[1px]">
									<span className="well flex size-14 shrink-0 flex-col items-center justify-center rounded-md">
										<span className="font-mono text-[20px] leading-none font-bold text-flag">
											{entry.score}
										</span>
									</span>
									<span className="min-w-0 flex-1">
										<span className="block text-[16px] leading-tight font-bold tracking-tight text-ink">
											{entry.verdict.title}
										</span>
										<span className="mt-0.5 block font-mono text-[11px] tracking-wider text-ink-faint uppercase">
											{entry.dateLabel} · {entry.timeLabel}
										</span>
									</span>
									<ChevronDown
										className="size-6 shrink-0 text-ink-faint transition-transform group-data-[panel-open]:rotate-180"
										strokeWidth={2.5}
									/>
								</Accordion.Trigger>
							</Accordion.Header>
							<Accordion.Panel className="px-3 pb-3">
								<p className="font-mono text-[10px] tracking-wider text-ink-faint uppercase">
									{m.log_rd_responses()}
								</p>
								<dl className="mt-1">
									{entry.responses.map((response) => (
										<div
											key={response.question}
											className="flex gap-2 border-b border-line py-1.5 last:border-0"
										>
											<dt className="min-w-0 flex-1 text-[13px] leading-snug text-ink-dim">
												{response.question}
											</dt>
											<dd className="shrink-0 text-[13px] leading-snug font-semibold text-ink">
												{response.answer}
											</dd>
										</div>
									))}
								</dl>
								<p className="mt-2 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
									{m.log_rd_conclusion()}
								</p>
								<div className="mt-1 flex flex-wrap gap-1.5">
									<span className={pill({ tone: 'gold' })}>{entry.verdict.tag}</span>
									{entry.flagTitles.map((title) => (
										<span key={title} className={pill({ tone: 'hot' })}>
											{title}
										</span>
									))}
									{entry.outcome == null ? null : (
										<span className={pill({ tone: 'teal' })}>
											{OUTCOME_LABEL[entry.outcome]?.() ?? entry.outcome}
										</span>
									)}
								</div>
							</Accordion.Panel>
						</Accordion.Item>
					))}
				</Accordion.Root>
			</Tabs.Panel>

			<Tabs.Panel value="activity">
				<Head right={<span>{log.activity.length}</span>}>{m.log_activity()}</Head>
				<div className="flex flex-col gap-2">
					{log.activity.map((entry, index) => (
						<Panel
							// Activity rows carry no id and repeat dates, so position is the
							// only identity the fixture offers.
							// biome-ignore lint/suspicious/noArrayIndexKey: fixture rows have no id
							key={index}
							accent={entry.color}
							className="flex items-center gap-3 py-3 pr-3 pl-5"
						>
							<span className={pill({ tone: 'chalk' })}>
								{ACTIVITY_LABEL[entry.type]?.() ?? entry.type}
							</span>
							<span className="min-w-0 flex-1">
								<span className="block text-[15px] leading-tight font-semibold text-ink">
									{entry.label}
								</span>
								{entry.note ? (
									<span className="mt-0.5 block text-[12px] leading-snug text-ink-dim">
										{entry.note}
									</span>
								) : null}
							</span>
							<span className="shrink-0 font-mono text-[11px] text-ink-faint">{entry.date}</span>
						</Panel>
					))}
				</div>
			</Tabs.Panel>
		</Tabs.Root>
	);
}

function SessionRow({ session }: { session: LoggedSessionFixture }) {
	return (
		<Accordion.Item value={session.iso} className="slab overflow-hidden rounded-lg">
			<Accordion.Header>
				<Accordion.Trigger className="group flex w-full items-center gap-3 px-3 py-3 text-left transition-transform duration-75 active:translate-y-[1px]">
					<span className="well flex size-14 shrink-0 flex-col items-center justify-center rounded-md">
						<span className="font-mono text-[11px] leading-none tracking-wider text-ink-faint uppercase">
							{session.weekdayLabel}
						</span>
						<span className="mt-1 font-mono text-[13px] leading-none font-bold text-chalk">
							{session.dateLabel}
						</span>
					</span>
					<span className="min-w-0 flex-1">
						<span className="block text-[16px] leading-tight font-bold tracking-tight text-ink">
							{session.dayType}
						</span>
						<span className="mt-0.5 block font-mono text-[11px] tracking-wider text-ink-faint uppercase">
							{m.sets_count({ n: session.setCount })}
							{session.durationMin == null ? '' : ` · ${session.durationMin} min`}
						</span>
					</span>
					<ChevronDown
						className="size-6 shrink-0 text-ink-faint transition-transform group-data-[panel-open]:rotate-180"
						strokeWidth={2.5}
					/>
				</Accordion.Trigger>
			</Accordion.Header>
			<Accordion.Panel className="px-3 pb-3">
				{session.exercises.map((exercise) => (
					<div key={exercise.exId} className="mt-2 first:mt-0">
						<p className="text-[14px] leading-tight font-semibold text-ink">{exercise.name}</p>
						<ul className="mt-1">
							{exercise.sets.map((set, index) => (
								<li
									// biome-ignore lint/suspicious/noArrayIndexKey: append-only list, no stable id in the fixture
									key={index}
									className="flex items-center gap-2 border-b border-line py-1 last:border-0"
								>
									<span className="w-6 shrink-0 font-mono text-[11px] text-ink-faint">
										{index + 1}
									</span>
									<span className="min-w-0 flex-1 truncate font-mono text-[12px] text-ink-dim">
										{setLine(set, exercise.fields)}
									</span>
									<span
										className="size-2.5 shrink-0 rounded-full"
										style={{ background: set.done ? 'var(--teal)' : 'var(--line)' }}
									/>
								</li>
							))}
						</ul>
					</div>
				))}
				{session.note ? (
					<p className="mt-3 border-t border-line pt-2 text-[13px] leading-snug text-ink-dim">
						{session.note}
					</p>
				) : null}
			</Accordion.Panel>
		</Accordion.Item>
	);
}

// src/routes/log/+page.svelte
<script lang="ts">
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '$lib/components/ui/accordion';
import { getContent } from '$lib/content';
import type { VerdictId } from '$lib/content/types';
import * as m from '$lib/paraglide/messages';
import { getLocale } from '$lib/paraglide/runtime';
import SectionHeading from '$lib/SectionHeading.svelte';
import SetRows from '$lib/SetRows.svelte';
import { appState } from '$lib/state.svelte';
import type { Col } from '$lib/trainColumns';
import { edgeLabel, weightLabel } from '$lib/units';

// Editable columns for past-workout sets (all fields; values are unit-aware).
const LOG_COLS: Col[] = [
	{ key: 'weight', label: weightLabel },
	{ key: 'edge', label: edgeLabel },
	{ key: 'time', label: m.field_time },
	{ key: 'reps', label: m.field_reps },
	{ key: 'grip', label: m.field_grip },
	{ key: 'rest', label: m.field_rest },
	{ key: 'rpe', label: m.field_rpe },
];

const typeLabel: Record<string, () => string> = {
	rec: m.log_type_rec,
	day: m.log_type_day,
	test: m.log_type_test,
};

const content = getContent();
// Post-session outcome, indexed by the stored value: 0 bailed · 1 flat · 2 as
// expected · 3 strong.
const OUTCOME_LABEL = [
	m.rd_outcome_bailed,
	m.rd_outcome_flat,
	m.rd_outcome_ok,
	m.rd_outcome_strong,
];

function remove(idx: number) {
	appState.log.splice(idx, 1);
}
function removeWorkout(idx: number) {
	appState.workouts.splice(idx, 1);
}
// readinessLog is stored oldest→newest, so removal is by identity (the list is
// reversed for display).
function removeReadiness(entry: (typeof appState.readinessLog)[number]) {
	const i = appState.readinessLog.indexOf(entry);
	if (i >= 0) appState.readinessLog.splice(i, 1);
}

/** Logged time-of-day (HH:MM) for an epoch-ms timestamp. */
const hour = (at: number) =>
	new Date(at).toLocaleTimeString(getLocale(), { hour: '2-digit', minute: '2-digit' });

/** Map a stored answers map back to readable question → chosen-answer pairs. */
function responses(answers?: Record<string, number>): { q: string; a: string }[] {
	if (!answers) return [];
	const out: { q: string; a: string }[] = [];
	for (const q of content.quiz) {
		const v = answers[q.id];
		if (v == null) continue;
		out.push({ q: q.q, a: q.a.find((o) => o.v === v)?.t ?? String(v) });
	}
	return out;
}

/** The conclusion's flag titles. */
const flagTitles = (flags?: { id: string }[]): string[] =>
	(flags ?? []).map((f) => content.flags[f.id]?.title ?? f.id);
</script>

<section class="animate-in fade-in duration-300">
	<SectionHeading title={m.sec_log()} />
	<p class="mb-[26px] max-w-[62ch] text-[15px] text-ink-dim">{m.lede_log()}</p>

	{#if appState.readinessLog.length > 0}
		<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">
			{m.log_readiness()}
		</h3>
		<Accordion type="multiple" class="mb-6 flex flex-col gap-2.5">
			{#each [...appState.readinessLog].reverse() as r, i (r)}
				{@const v = content.verdicts[r.verdict as VerdictId]}
				<AccordionItem value={`r${i}`} class="rounded-xl border border-line bg-panel last:border-b">
					<AccordionTrigger class="px-4 py-3 hover:no-underline">
						<span class="font-mono text-xs text-ink-faint">{r.date} · {hour(r.at)}</span>
						<span
							class="ml-2 flex-none rounded-md px-2 py-0.5 font-mono text-[11px] font-bold tabular-nums"
							style:background="color-mix(in srgb, {v?.color ?? 'var(--ink-faint)'} 18%, transparent)"
							style:color={v?.color ?? 'var(--ink-faint)'}
						>
							{r.score}
						</span>
						<span class="ml-2 flex-1 text-left text-[13px]">
							<b class="text-chalk">{v?.title ?? r.verdict}</b>{#if r.outcome != null}<span
									class="text-ink-faint"
								>
									· {OUTCOME_LABEL[r.outcome]?.() ?? ''}</span
								>{/if}
						</span>
					</AccordionTrigger>
					<AccordionContent class="px-4 pb-4">
						{#if responses(r.answers).length}
							<div class="mb-1.5 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
								{m.log_rd_responses()}
							</div>
							<div class="mb-3 flex flex-col gap-1">
								{#each responses(r.answers) as row (row.q)}
									<div class="flex items-baseline justify-between gap-3 text-[13px]">
										<span class="text-ink-dim">{row.q}</span>
										<span class="flex-none font-semibold text-chalk">{row.a}</span>
									</div>
								{/each}
							</div>
						{/if}
						<div class="mb-1.5 font-mono text-[10px] tracking-wider text-ink-faint uppercase">
							{m.log_rd_conclusion()}
						</div>
						<p class="text-[13px] text-ink-dim">
							<b class="text-chalk">{v?.title ?? r.verdict}</b>
						</p>
						{#if flagTitles(r.flags).length}
							<div class="mt-2 flex flex-wrap gap-1.5">
								{#each flagTitles(r.flags) as t (t)}
									<span class="rounded-full border border-line px-2 py-0.5 text-[11px] text-ink-dim">
										{t}
									</span>
								{/each}
							</div>
						{/if}
						<button
							type="button"
							class="mt-3 font-mono text-[10px] tracking-wider text-ink-faint uppercase hover:text-flag"
							onclick={() => removeReadiness(r)}
						>
							✕ {m.btn_delete()}
						</button>
					</AccordionContent>
				</AccordionItem>
			{/each}
		</Accordion>
	{/if}

	{#if appState.workouts.length > 0}
		<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">
			{m.log_workouts()}
		</h3>
		<Accordion type="multiple" class="mb-6 flex flex-col gap-2.5">
			{#each appState.workouts.slice(0, 60) as w, idx (w)}
				<AccordionItem value={`w${idx}`} class="rounded-xl border border-line bg-panel last:border-b">
					<AccordionTrigger class="px-4 py-3 hover:no-underline">
						<span class="font-mono text-xs text-ink-faint">{w.date}</span>
						<span class="ml-2 flex-1 text-left text-[13px]">
							<b class="text-chalk">{w.day}</b>
							<span class="text-ink-faint">· {w.exercises.length}×</span>
						</span>
					</AccordionTrigger>
					<AccordionContent class="px-4 pb-4">
						{#each w.exercises as ex (ex.exId)}
							<div class="mb-2.5">
								<div class="mb-1 text-[13px] font-semibold text-chalk">{ex.name}</div>
								<SetRows rows={ex.sets} cols={LOG_COLS} onRemove={(i) => ex.sets.splice(i, 1)} />
							</div>
						{/each}
						{#if w.note}<p class="text-[12px] text-ink-dim italic">“{w.note}”</p>{/if}
						<button
							type="button"
							class="mt-2 font-mono text-[10px] tracking-wider text-ink-faint uppercase hover:text-flag"
							onclick={() => removeWorkout(idx)}
						>
							✕ {m.btn_delete()}
						</button>
					</AccordionContent>
				</AccordionItem>
			{/each}
		</Accordion>
	{/if}

	<h3 class="mb-2 font-mono text-[11px] tracking-wider text-ink-faint uppercase">{m.log_activity()}</h3>
	{#if appState.log.length === 0}
		<div class="rounded-xl border border-dashed border-line px-5 py-[46px] text-center text-sm text-ink-faint">
			{m.log_empty()}
		</div>
	{:else}
		<div class="flex flex-col gap-2.5">
			{#each appState.log.slice(0, 120) as entry, idx (entry)}
				<div class="flex items-center gap-3.5 rounded-[10px] border border-line bg-panel px-4 py-3.5">
					<span class="w-[90px] flex-none font-mono text-xs text-ink-faint">{entry.date}</span>
					<span
						class="flex-none rounded-md px-2.5 py-1 font-mono text-[10px] font-bold tracking-wide uppercase"
						style:background="color-mix(in srgb, {entry.color} 18%, transparent)"
						style:color={entry.color}
					>
						{typeLabel[entry.type]?.() ?? entry.type}
					</span>
					<span class="flex-1 text-[13px] text-ink-dim">
						<b class="text-chalk">{entry.label}</b>{entry.note ? ` · ${entry.note}` : ''}
					</span>
					<button
						type="button"
						title="delete"
						onclick={() => remove(idx)}
						class="px-1 text-base text-ink-faint transition hover:text-flag"
					>
						✕
					</button>
				</div>
			{/each}
		</div>
	{/if}
</section>
